"""initial schema

Revision ID: 1c0a31f1078f
Revises: 
Create Date: 2026-09-22 21:22:38.710388
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = '1c0a31f1078f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('face_consent', sa.Boolean(), nullable=False),
    sa.Column('face_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_demo_data'), 'customers', ['demo_data'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_category_code'), 'product_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_product_categories_demo_data'), 'product_categories', ['demo_data'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_table('touchpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('touchpoint_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_order')
    )
    op.create_index(op.f('ix_touchpoints_demo_data'), 'touchpoints', ['demo_data'], unique=False)
    op.create_index(op.f('ix_touchpoints_touchpoint_code'), 'touchpoints', ['touchpoint_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='role', native_enum=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('face_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('embedding', Vector(512).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_templates_active'), 'face_templates', ['active'], unique=False)
    op.create_index(op.f('ix_face_templates_customer_id'), 'face_templates', ['customer_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='recordstatus', native_enum=False), nullable=False),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_demo_data'), 'products', ['demo_data'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='visitstatus', native_enum=False), nullable=False),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visits_demo_data'), 'visits', ['demo_data'], unique=False)
    op.create_index(op.f('ix_visits_started_at'), 'visits', ['started_at'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index('uq_active_visit_customer', 'visits', ['customer_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('touchpoint_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('expression_label', sa.String(length=32), nullable=True),
    sa.Column('expression_confidence', sa.Float(), nullable=True),
    sa.Column('expression_scores', sa.JSON(), nullable=True),
    sa.Column('face_match_distance', sa.Float(), nullable=True),
    sa.Column('image_status', sa.String(length=32), nullable=False),
    sa.Column('expression_status', sa.String(length=32), nullable=False),
    sa.Column('identity_status', sa.String(length=32), nullable=False),
    sa.Column('detector_version', sa.String(length=255), nullable=True),
    sa.Column('emotion_model_version', sa.String(length=255), nullable=True),
    sa.Column('recognition_model_version', sa.String(length=255), nullable=True),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['touchpoint_id'], ['touchpoints.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_customer_id'), 'observations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_observations_demo_data'), 'observations', ['demo_data'], unique=False)
    op.create_index(op.f('ix_observations_event_id'), 'observations', ['event_id'], unique=True)
    op.create_index(op.f('ix_observations_expression_label'), 'observations', ['expression_label'], unique=False)
    op.create_index(op.f('ix_observations_expression_status'), 'observations', ['expression_status'], unique=False)
    op.create_index(op.f('ix_observations_identity_status'), 'observations', ['identity_status'], unique=False)
    op.create_index(op.f('ix_observations_image_status'), 'observations', ['image_status'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_touchpoint_id'), 'observations', ['touchpoint_id'], unique=False)
    op.create_index(op.f('ix_observations_visit_id'), 'observations', ['visit_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_demo_data'), 'orders', ['demo_data'], unique=False)
    op.create_index(op.f('ix_orders_external_code'), 'orders', ['external_code'], unique=True)
    op.create_index(op.f('ix_orders_ordered_at'), 'orders', ['ordered_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_visit_id'), 'orders', ['visit_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_code_snapshot', sa.String(length=64), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_visit_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_ordered_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_demo_data'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_observations_visit_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_touchpoint_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_image_status'), table_name='observations')
    op.drop_index(op.f('ix_observations_identity_status'), table_name='observations')
    op.drop_index(op.f('ix_observations_expression_status'), table_name='observations')
    op.drop_index(op.f('ix_observations_expression_label'), table_name='observations')
    op.drop_index(op.f('ix_observations_event_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_demo_data'), table_name='observations')
    op.drop_index(op.f('ix_observations_customer_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index('uq_active_visit_customer', table_name='visits', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_started_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_demo_data'), table_name='visits')
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_demo_data'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_face_templates_customer_id'), table_name='face_templates')
    op.drop_index(op.f('ix_face_templates_active'), table_name='face_templates')
    op.drop_table('face_templates')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_touchpoints_touchpoint_code'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_demo_data'), table_name='touchpoints')
    op.drop_table('touchpoints')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_demo_data'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_category_code'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_demo_data'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
